refactor(ci): reorder jobs in workflow #9

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,13 +24,6 @@ jobs:
           set -o pipefail
           make all 2>&1 | tee build.log
 
-      - name: Collect logs
-        if: always()
-        shell: bash
-        run: |
-          grep -niE '(^|[[:space:]])error:' build.log > errors.txt || true
-          grep -i "warning" build.log > warnings.txt || true
-      
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -46,6 +39,13 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/epoll-web-server:latest
 
+      - name: Collect logs
+        if: always()
+        shell: bash
+        run: |
+          grep -niE '(^|[[:space:]])error:' build.log > errors.txt || true
+          grep -i "warning" build.log > warnings.txt || true
+      
       - name: Comment to PR
         if: github.event_name == 'pull_request' && always()
         uses: actions/github-script@v7
